### ISSUE TITLE
Fix no records returned by Sierra API throwing an exception

### ISSUE THREAD

**Issue by kfriedman** [NYPL-discovery/sierraupdatepoller#10]
Right now, if the Sierra API returns no records with the `fields` parameter specified, it throws a null pointer exception. It should, instead, consider this "normal" behavior and retry the route normally.

**Comment by jmathewt** [comment]
Fixed. Sent it to @kfriedman for review.

**Comment by jmathewt** [comment]
Checking using optional:

Optional<Integer> optionalTotal = Optional
            .ofNullable((Integer) apiResponse.get(HarvesterConstants.SIERRA_API_RESPONSE_TOTAL));

        if (optionalTotal.isPresent()) {
             //  embrace the response and process it
        }
