### ISSUE TITLE
Ensure that while updating redis cache all keys get updated

### ISSUE THREAD

**Issue by jmathewt** [NYPL-discovery/sierraupdatepoller#24]
Recently, it was found that the redis cache had key updated for bibs in redis as:

```
placeholder_cache_redis:6379> hgetall bibs
1) "isComplete"
2) "true"
```
instead of:

```
1) "bibsUpdatePoller:lastUpdatedOffset"
2) "33"
3) "bibsUpdatePoller:endTimeDelta"
4) "2017-05-19T20:47:25Z"
5) "bibsUpdatePoller:beginTimeDelta"
6) "2017-05-19T00:00:00Z"
7) "isComplete"
8) "true"
```
After the initial analysis the only reason I think this happened was somehow either  because of an error that occurred in the ResourceIdProcessor or a case occurred where the ResourceIdProcessor didn't had to update the redis cache and continued in the route and CacheComplete updated the redis Server. 

I will do some testing around this to confirm this could be the case. For now, the logical resolution is for CacheComplete to update redis only if the ResourceIdProcessor was able to successfully update the cache.

**Comment by jmathewt** [comment]
Want another pair of eyes to look at my logic. Have asked @kfriedman to take a look.

**Comment by jmathewt** [comment]
Following are the changes made:

1. CacheMonitor will make sure that - lastUpdatedOffset, endTimeDelta, beginTimeDelta and isComplete are present, in order to use the fields from cache.

2. ResourceIdMonitor - will post to kinesis all the records that it gets from each sierra api query and update the start time, end time and offset in redis cache and return status as true for processed

3. CacheComplete -  will set isComplete to true only if it received true for processed from ResourceIdMonitor.

**Comment by kfriedman** [comment]
This looks really good. Spent a few hours today looking at it, running it and trying to break it to cause inconsistent behavior. It seemed to handle all the cases well. Nice work!
