### ISSUE TITLE
Deploy to sandbox with Elastic Beanstalk

### ISSUE THREAD

**Issue by kfriedman** [NYPL-discovery/sierraupdatepoller#8]

**Comment by jmathewt** [comment]
@gkallenberg,
I have merged excepton_handling branch changes to master branch. Master branch can be used for deployment.

**Comment by jmathewt** [comment]
@gkallenberg helped me to get EB configuration set up on my machine.  The app has been deployed and is running from the master branch.

**Comment by jmathewt** [comment]
This issue can be closed. We have EB setup for deployment.
